[project]
name = 'play-to-earn-gaming-tokens'
description = ''
authors = []
telemetry = true
cache_dir = './.cache'
requirements = []
[contracts.achievement-rewards]
path = 'contracts/achievement-rewards.clar'
clarity_version = 2
epoch = 2.5

[contracts.game-token]
path = 'contracts/game-token.clar'
clarity_version = 2
epoch = 2.5
[repl.analysis]
passes = ['check_checker']

[repl.analysis.check_checker]
strict = false
trusted_sender = false
trusted_caller = false
callee_filter = false
